# Generated by Django 3.0.3 on 2020-10-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Ccылка на профиль Фейсбук'),
        ),
        migrations.AddField(
            model_name='bio',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Ccылка на Телеграм'),
        ),
    ]
