# Generated by Django 3.0.3 on 2020-09-28 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='face/', verbose_name='Аватар')),
            ],
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to='uploads/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galery.Projects',
                                    verbose_name='Проект'),
        ),
    ]
