# Generated by Django 3.0.3 on 2020-10-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('galery', '0002_auto_20200928_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bio',
            options={'verbose_name': 'Блок биографии', 'verbose_name_plural': 'Блок биографии'},
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to='uploads/', verbose_name='Изображение'),
        ),
    ]
