# Generated by Django 3.0.3 on 2020-10-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('galery', '0003_auto_20201002_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='uploads/'),
        ),
    ]
