# Generated by Django 3.0.3 on 2020-10-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('galery', '0004_photos_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='medium',
            field=models.ImageField(editable=False, null=True, upload_to='uploads/'),
        ),
    ]
