# Generated by Django 3.0.3 on 2020-10-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('galery', '0005_photos_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='text',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
