# Generated by Django 3.0.3 on 2020-10-03 10:20

import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('galery', '0006_auto_20201002_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='medium',
            field=sorl.thumbnail.fields.ImageField(editable=False, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(upload_to='uploads/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(editable=False, null=True, upload_to='uploads/'),
        ),
    ]
