# Generated by Django 3.0.3 on 2020-10-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('galery', '0007_auto_20201003_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название раздела')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.RemoveField(
            model_name='photos',
            name='medium',
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to='uploads/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='thumbnail',
            field=models.ImageField(editable=False, upload_to='thumbs'),
        ),
        migrations.AddField(
            model_name='projects',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galery.ProjectTypes',
                                    verbose_name='Раздел'),
        ),
    ]
