# Generated by Django 3.0.3 on 2020-10-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('galery', '0008_auto_20201003_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttypes',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
