# Generated by Django 3.0.3 on 2020-10-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('galery', '0009_projecttypes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttypes',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
