# Generated by Django 3.0.3 on 2020-10-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('galery', '0010_auto_20201004_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='projecttypes',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Поле заполняется автоматически'),
        ),
    ]
